# Generated by Django 3.2.9 on 2021-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('number', models.IntegerField()),
                ('code_number', models.CharField(default='brand+năm+số TT 2 số (ex: aruba202101)', max_length=50)),
                ('brand', models.CharField(choices=[('Mikrotik', 'Mikrotik'), ('TPLink', 'TPLink'), ('Aruba', 'Aruba'), ('Unifi', 'Unifi'), ('Dahua', 'Dahua'), ('Phụ kiện, thiết bị quang', 'Optical equipment'), ('Khác', 'Other')], default='Mikrotik', max_length=100)),
                ('status', models.CharField(choices=[('Còn hàng', 'Còn hàng'), ('Hết hàng', 'Hết hàng'), ('Khác', 'Other')], default='Còn hàng', max_length=100)),
                ('price', models.CharField(default='Nhập giá VNĐ', max_length=50)),
                ('aruba', models.CharField(default=None, max_length=100)),
                ('mikrotik', models.CharField(default=None, max_length=100)),
                ('tplink', models.CharField(default=None, max_length=100)),
                ('unifi', models.CharField(default=None, max_length=100)),
                ('description', models.TextField()),
                ('picture1', models.ImageField(upload_to='static/images/pictue_up')),
                ('picture2', models.ImageField(null=True, upload_to='static/images/pictue_up')),
                ('data_sheet', models.FileField(null=True, upload_to='static/images/file_up')),
            ],
        ),
    ]
