# Generated by Django 3.2.9 on 2021-11-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aruba',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mikrotik',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tplink',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unifi',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
