# Generated by Django 3.2.9 on 2021-11-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211107_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aruba',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
