# Generated by Django 3.2.9 on 2021-11-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_aruba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='aruba',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mikrotik',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tplink',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unifi',
        ),
        migrations.AddField(
            model_name='product',
            name='classify',
            field=models.CharField(choices=[('Router', 'Router'), ('Wifi', 'Wifi'), ('Camera', 'Camera'), ('Switch/Hub', 'Switch/Hub'), ('Khác', 'Other')], default='Other', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('Mikrotik', 'Mikrotik'), ('TPLink', 'TPLink'), ('Aruba', 'Aruba'), ('Unifi', 'Unifi'), ('Dahua', 'Dahua'), ('Phụ kiện, thiết bị quang', 'Optical equipment'), ('Khác', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='code_number',
            field=models.CharField(default='brand+năm+số TT 2 số (ex: aruba202101)', max_length=100),
        ),
    ]
