# Generated by Django 3.2.9 on 2021-11-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_code_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
