# Generated by Django 3.2.9 on 2021-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_sheet',
            field=models.FileField(blank=True, upload_to='static/images/file_up'),
        ),
    ]
